# Generated by Django 4.1 on 2022-09-06 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=52, null=True)),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=1024)),
                ('finished', models.BooleanField(default=False)),
                ('time_to_exit', models.CharField(blank=True, max_length=255, null=True)),
                ('maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_maker_id', to='clients.clients')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user_id', to='clients.clients')),
            ],
            options={
                'verbose_name': 'Messages',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
