# Generated by Django 4.1 on 2022-09-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='ClientsModel',
        ),
    ]
