# Generated by Django 4.1 on 2022-09-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_messages_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsmodel',
            name='id_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
